# fly.toml app configuration file generated for fast-api-project-improved on 2026-01-29T18:54:03+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'fast-api-project-improved'
primary_region = 'fra'

[build]

[http_service]
  internal_port = 8501        # Streamlit bu porttan yayın yapıyor
  force_https = true
  auto_stop_machines = false  # Bu, uygulamanın kapanmasını engeller
  auto_start_machines = true
  min_machines_running = 1

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
